MayLocNuoc/Controllers/DangNhapController.cs
using MayLocNuoc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MayLocNuoc.Controllers
{
    public class DangNhapController : Controller
    {
        mayLocNuocEntities db = new mayLocNuocEntities();
        // GET: DangNhap
        public ActionResult Log()
        {

            return View();
        }
        public ActionResult registration()
        {

            return View();
        }
        public ActionResult registGetPasswordration()
        {

            return View();
        }
        public ActionResult changePassword()
        {

            return View();
        }
        [HttpPost]
        public JsonResult themtaikhoan(string a, string b, string c, string d, string e, string g)
        {
            string avg = "";
            if (KyTu.kiemtra(a) == true || KyTu.kiemtra(b) == true || KyTu.kiemtra(c) == true || KyTu.kiemtra(d) == true || KyTu.kiemtra(e) == true)
            {
                avg = "Không được nhập Ký tự đặc biệt chỉ có thể nhập a-z 0-9";
            }
            else
            {

                //tim so dien thoai
                try
                {
                    if (db.infoes.Where(n => n.number_phone == a).Count() != 0)
                    {
                        avg = "Số điện thoại đã được sử dụng";
                    }
                    else
                    {
                        if (db.accs.Where(n => n.taikhoan == a).Count() != 0)
                        {
                            avg = "sdt đã có tài khoản đăng ký";
                        }
                        else
                        {
                            try
                            {
                                acc ac = new acc();
                                ac.taikhoan = a;
                                ac.matkhau = MD5.ToMD5(b.Trim());
                                ac.daxoa = false;
                                ac.email = g;
                                ac.chucvu = 3;
                                ac.taikhoanquanly = "ADminVip";

                                info inf = new info();
                                inf.nameFull = d;
                                inf.age = Convert.ToInt32(e.Trim());
                                inf.adress = c;
                                inf.number_phone = a;
                                inf.taikhoan = a;

                                db.accs.Add(ac);
                                db.infoes.Add(inf);
                                db.SaveChanges();
                                avg = "Cảm Ơn Bạn Đã sử dụng dịch vụ của chúng tôi";
                            }
                            catch (Exception)
                            {

                                avg = "đã có lỗi sảy ra ";
                            }

                        }
                    }
                }
                catch
                {
                    avg = "404";
                }


            }

            return Json(avg);
        }
        public JsonResult LogJson(string taikhoan, string matkhau)
        {
            /*
             * -1 là có lỗi xảy ra
             * 0 la tai khoan khong chinh xac
             * 1 là mạt khẩu không chính xác
             * đăng nhập thành công xác định là admin hay người dùng
             * 2 là người dùng 
             * 3 là loại khonmg cho đăng nhập trang này 
             */
            string trave = "";
            try
            {


                int c = db.accs.Where(n => n.taikhoan == taikhoan).Count();
                if (c == 1)
                {
                    string avc = MD5.ToMD5(matkhau.Trim());
                    int m = db.accs.Where(n => n.matkhau == avc && n.taikhoan == taikhoan).Count();
                    if (m == 1)
                    {
                        var k = db.accs.Where(n => n.taikhoan == taikhoan && n.matkhau == avc).FirstOrDefault();
                        if (k.chucvu == 3)
                        {
                            //luu cookie
                            save.taikhoan = taikhoan.Trim();
                            HttpCookie ck = new HttpCookie("Máy Lọc Nước Sơn Trần");
                            ck.Value = maHoa.mahoa(taikhoan + "1507" + MD5.ToMD5(matkhau.Trim()));
                            ck.Expires = DateTime.Now.AddDays(15);
                            Response.Cookies.Add(ck);
                            //luu section 
                            trave = "2";//trave roi chuyen trang
                        }
                        else
                        {
                            trave = "3";
                        }
                    }
                    else
                    {
                        trave = "1";
                    }
                }
                else
                {
                    trave = "0";
                }
            }
            catch (Exception)
            {

                trave = "-1";
            }
            return Json(trave);
        }
        public JsonResult registGetPasswordrationJson(string AccdanhNhap_Email, string EmailLayPass)
        {
            /*
             * 1 la tai khoan khong chinh xac
             * 2 la gmail khong chinh xac 
             * 3 la thanh cong 
             * 0 la he thong gap loi
             */
            string Trave = "";
            try
            {
                if (db.accs.Where(n => n.taikhoan == AccdanhNhap_Email).Count() == 1)
                {
                    if (db.accs.Where(n => n.taikhoan == AccdanhNhap_Email && n.email == EmailLayPass).Count() == 1)
                    {
                        guiMail gm = new guiMail();
                        Ran r = new Ran();
                        if (gm.ToguiMail(EmailLayPass, r.songaunhien().ToString()) == true)
                        {
                            Trave = "3";
                        }
                        else
                        {
                            Trave = "0";
                        }
                    }
                    else
                    {
                        Trave = "2";
                    }
                }
                else
                {
                    Trave = "1";
                }
            }
            catch (Exception)
            {

                Trave = "0";
            }
            return Json(Trave);
        }
        //changPass
        public JsonResult changePasswordJson(string taikhoanthaydoi, string passOld, string passNew)
        {
            /*
             * 1 trong co ky tu dac biet
             * 2 hệ thống gặp lỗi 
             * 3 tai khoan khong chinh xac
             * 4 mat khau khong chinh xac
             * 5 mat khau da duowc thay doi
             */
            string avg = "";
            try
            {
                if (KyTu.kiemtra(taikhoanthaydoi) == true || KyTu.kiemtra(passOld) == true || KyTu.kiemtra(passNew) == true)
                {
                    avg = "1";
                }
                else
                {
                    if (db.accs.Where(n => n.taikhoan == taikhoanthaydoi).Count() == 1)
                    {
                        var mkOld = MD5.ToMD5(passOld.Trim());
                        if (db.accs.Where(n => n.taikhoan == taikhoanthaydoi && n.matkhau == mkOld).Count() == 1)
                        {
                            var ChangPassss = db.accs.Where(n => n.taikhoan == taikhoanthaydoi && n.matkhau == mkOld).FirstOrDefault();

                            ChangPassss.matkhau = MD5.ToMD5(passNew.Trim());

                            db.SaveChanges();
                            avg = "5";
                        }
                        else
                        {
                            avg = "4";
                        }
                    }
                    else
                    {
                        avg = "3";
                    }
                }
            }
            catch (Exception)
            {

                avg = "2";
            }


            return Json(avg);
        }

        //add product in database
        //changPass
        public JsonResult RegistrationJson(string AccRegistration, string PassRegistration,
                string NameRegistration, string numberPhoneRegistration,
               string AdressRegistration, string EmailRegistration)
        {
            /*
             * 1 trong co ky tu dac biet
             * 2 kiem tra nay tai khoan da co chuwa 
             * 3 kiem tra xem da co gmail nay chua
             * 4 co loi he thong
             * 5  thanh cong 
             */
            string Trave = "";
            try
            {
                if (AccRegistration==null || AccRegistration==""||
                    PassRegistration == null || PassRegistration == "" ||
                    NameRegistration == null || NameRegistration == "" ||
                    numberPhoneRegistration == null || numberPhoneRegistration == "" ||
                    AdressRegistration == null || AdressRegistration == "" ||
                    EmailRegistration == null || EmailRegistration == "" )
                {
                    Trave = "6";
                }
                else
                {
                    if (KyTu.kiemtra(AccRegistration) == true || KyTu.kiemtra(PassRegistration) == true ||
                                        KyTu.kiemtra(NameRegistration) == true || KyTu.kiemtra(numberPhoneRegistration) == true ||
                                        KyTu.kiemtra(AdressRegistration) == true || KyTu.kiemtra(EmailRegistration) == true)
                    {
                        Trave = "1";
                    }
                    else
                    {
                        if (db.accs.Where(n => n.taikhoan == AccRegistration).Count() == 0)
                        {

MayLocNuoc/Views/DangNhap/Log.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Máy Lọc Nước Sơn Trần - Đăng Nhập Tài Khoản</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Trendy Login Form template Responsive, Login form web template,Flat Pricing tables,Flat Drop downs  Sign up Web Templates, Flat Web Templates, Login sign up Responsive web template, SmartPhone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- Custom Theme files -->
    <link href="~/Content/Log/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <!-- //Custom Theme files -->
    <!-- web font -->
    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'><!--web font-->
    <!-- //web font -->
    <script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
    <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    <!-- main -->
    <div class="agileits-main">
        <div class="w3top-nav">
            <div class="w3top-nav-left">
                <h1><a href="@Url.Action("Index","Product")">Sơn Trần</a></h1>
            </div>
            <div class="w3top-nav-right">
                <ul>
                    <li><a href="@Url.Action("Index","Product")" class="active">Home</a></li>
                    <li><a href="@Url.Action("Log","DangNhap")">Đăng Nhập</a></li>
                    <li><a href="@Url.Action("registration","DangNhap")">Đăng Ký</a></li>
                    <li><a href="@Url.Action("registGetPasswordration","DangNhap")">Quên Mật Khẩu</a></li>
                    <li><a href="@Url.Action("changePassword","DangNhap")">Đổi Mật Khẩu</a></li>
                    <li><a href="@Url.Action("DN","QuanTri")">Tư Cách Khác</a></li>
                </ul>
            </div>
            <div class="clear"></div>
        </div>
        <div class="header-main">
            <h2>Đăng Nhập</h2>
            <div class="header-bottom">
                <div class="header-right w3agile">
                    <div class="header-left-bottom agileinfo">                       
                            <div class="icon1">
                                <input type="text" id="AccdanhNhap" placeholder="Tài Khoản Của Bạn" required="" />
                            </div>
                            <div class="icon1">
                                <input type="password"  id="passdanhNhap" placeholder="Mật Khẩu Của Bạn" required="" />
                            </div>
                            <div class="bottom">
                                <input type="submit" id="btnLog_DanhNhap" value="Đăng Nhập" />
                            </div>                   
                    </div>
                </div>
            </div>
        </div>

    </div>
    <!-- //main -->
    <!-- copyright -->
    <div class="copyright w3-agile">
        <p>© 2020 Máy Lọc Nước Sơn Trần  | Design by <a href="" target="_blank">HaiNam</a></p>
    </div>
    <!-- //copyright -->
    <script src="~/Content/Log/Log.js"></script>
</body>
</html>

MayLocNuoc/Views/DangNhap/changePassword.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Máy Lọc Nước Sơn Trần - Đổi Mật Khẩu</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Trendy Login Form template Responsive, Login form web template,Flat Pricing tables,Flat Drop downs  Sign up Web Templates, Flat Web Templates, Login sign up Responsive web template, SmartPhone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- Custom Theme files -->
    <link href="~/Content/Log/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <!-- //Custom Theme files -->
    <!-- web font -->
    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'><!--web font-->
    <!-- //web font -->
    <script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
    <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    <!-- main -->
    <div class="agileits-main">
        <div class="w3top-nav">
            <div class="w3top-nav-left">
                <h1><a href="@Url.Action("Index","Product")">Sơn Trần</a></h1>
            </div>
            <div class="w3top-nav-right">
                <ul>
                    <li><a href="@Url.Action("Index","Product")" class="active">Home</a></li>
                    <li><a href="@Url.Action("Log","DangNhap")">Đăng Nhập</a></li>
                    <li><a href="@Url.Action("registration","DangNhap")">Đăng Ký</a></li>
                    <li><a href="@Url.Action("registGetPasswordration","DangNhap")">Quên Mật Khẩu</a></li>
                    <li><a href="@Url.Action("changePassword","DangNhap")">Đổi Mật Khẩu</a></li>
                    <li><a href="@Url.Action("DN","QuanTri")">Tư Cách Khác</a></li>
                </ul>
            </div>
            <div class="clear"></div>
        </div>
        <div class="header-main">
            <h2>Đổi Mật Khẩu</h2>
            <div class="header-bottom">
                <div class="header-right w3agile">
                    <div class="header-left-bottom agileinfo">
                        <div class="icon1">
                            <input type="text" id="taikhoanthaydoi" placeholder="Tài Khoản" required="" />
                        </div>
                        <div class="icon1">
                            <input type="password" id="passOld" placeholder="Mật Khẩu Cũ" required="" />
                        </div>
                        <div class="icon1">
                            <input type="password" id="passNew" placeholder="Mật Khẩu Mới" required="" />
                        </div>
                        <div class="icon1">
                            <input type="password" id="PassAgain" placeholder="Mật Khẩu Nhập Lại" required="" />
                        </div>
                        <div class="bottom">
                            <input type="submit" id="btnChangePassword" value="Đổi Mật Khẩu" />
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <!-- //main -->
    <!-- copyright -->
    <div class="copyright w3-agile">
        <p>© 2020 Máy Lọc Nước Sơn Trần  | Design by <a href="" target="_blank">HaiNam</a></p>
    </div>
    <!-- //copyright -->
    <script src="~/Content/Log/Log.js"></script>
</body>
</html>

MayLocNuoc/Views/DangNhap/registGetPasswordration.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Máy Lọc Nước Sơn Trần - Quên Mật Khẩu</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Trendy Login Form template Responsive, Login form web template,Flat Pricing tables,Flat Drop downs  Sign up Web Templates, Flat Web Templates, Login sign up Responsive web template, SmartPhone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- Custom Theme files -->
    <link href="~/Content/Log/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <!-- //Custom Theme files -->
    <!-- web font -->
    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'><!--web font-->
    <!-- //web font -->
    <script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
    <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    <!-- main -->
    <div class="agileits-main">
        <div class="w3top-nav">
            <div class="w3top-nav-left">
                <h1><a href="@Url.Action("Index","Product")">Sơn Trần</a></h1>
            </div>
            <div class="w3top-nav-right">
                <ul>
                    <li><a href="@Url.Action("Index","Product")" class="active">Home</a></li>
                    <li><a href="@Url.Action("Log","DangNhap")">Đăng Nhập</a></li>
                    <li><a href="@Url.Action("registration","DangNhap")">Đăng Ký</a></li>
                    <li><a href="@Url.Action("registGetPasswordration","DangNhap")">Quên Mật Khẩu</a></li>
                    <li><a href="@Url.Action("changePassword","DangNhap")">Đổi Mật Khẩu</a></li>
                    <li><a href="@Url.Action("DN","QuanTri")">Tư Cách Khác</a></li>
                </ul>
            </div>
            <div class="clear"></div>
        </div>
        <div class="header-main">
            <h2>Quên Mật Khẩu</h2>
            <div class="header-bottom">
                <div class="header-right w3agile">
                    <div class="header-left-bottom agileinfo">
                        <div class="icon1">
                            <input type="text" id="AccdanhNhap_Email" placeholder="Tài Khoản Của Bạn" required="" />
                        </div>
                        <div class="icon1">
                            <input type="email" id="EmailLayPass" placeholder="Email@example.com" required="" />
                        </div>
                        <div class="bottom">
                            <input type="submit" id="BtnLayPass" value="Lấy Mật Khẩu" />
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <!-- //main -->
    <!-- copyright -->
    <div class="copyright w3-agile">
        <p>© 2020 Máy Lọc Nước Sơn Trần  | Design by <a href="" target="_blank">HaiNam</a></p>
    </div>
    <!-- //copyright -->
    <script src="~/Content/Log/Log.js"></script>
</body>
</html>

MayLocNuoc/Views/DangNhap/registration.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Máy Lọc Nước Sơn Trần - Đăng Ký Tài Khoản</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Trendy Login Form template Responsive, Login form web template,Flat Pricing tables,Flat Drop downs  Sign up Web Templates, Flat Web Templates, Login sign up Responsive web template, SmartPhone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- Custom Theme files -->
    <link href="~/Content/Log/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <!-- //Custom Theme files -->
    <!-- web font -->
    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'><!--web font-->
    <!-- //web font -->
    <script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
    <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    <!-- main -->
    <div class="agileits-main">
        <div class="w3top-nav">
            <div class="w3top-nav-left">
                <h1><a href="@Url.Action("Index","Product")">Sơn Trần</a></h1>
            </div>
            <div class="w3top-nav-right">
                <ul>
                    <li><a href="@Url.Action("Index","Product")" class="active">Home</a></li>
                    <li><a href="@Url.Action("Log","DangNhap")">Đăng Nhập</a></li>
                    <li><a href="@Url.Action("registration","DangNhap")">Đăng Ký</a></li>
                    <li><a href="@Url.Action("registGetPasswordration","DangNhap")">Quên Mật Khẩu</a></li>
                    <li><a href="@Url.Action("changePassword","DangNhap")">Đổi Mật Khẩu</a></li>
                    <li><a href="@Url.Action("DN","QuanTri")">Tư Cách Khác</a></li>
                </ul>
            </div>
            <div class="clear"></div>
        </div>
        <div class="header-main">
            <h2>Đăng Ký Tài Khoản</h2>
            <div class="header-bottom">
                <div class="header-right w3agile">
                    <div class="header-left-bottom agileinfo">
                        <div class="icon1">
                            <input type="text" id="AccRegistration" placeholder="Tài Khoản" required="" />
                        </div>
                        <div class="icon1">
                            <input type="password" id="PassRegistration" placeholder="Mật Khẩu " required="" />
                        </div>
                        <div class="icon1">
                            <input type="password" id="PassAgainRegistration" placeholder="Nhập lại Mật Khẩu" required="" />
                        </div>
                        <div class="icon1">
                            <input type="text" id="NameRegistration" placeholder="Tên Đầy Đủ" required="" />
                        </div>
                        <div class="icon1">
                            <input type="text" id="numberPhoneRegistration" placeholder="Số Điện Thoại" required="" />
                        </div>
                        <div class="icon1">
                            <input type="text" id="AdressRegistration" placeholder="Địa Chỉ " required="" />
                        </div>
                        <div class="icon1">
                            <input type="email" id="EmailRegistration" placeholder="Email của Bạn" required="" />
                        </div>
                        <div class="bottom">
                            <input type="submit" id="Btn_Registration" value="Log in" />
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <!-- //main -->
    <!-- copyright -->
    <div class="copyright w3-agile">
        <p>© 2020 Máy Lọc Nước Sơn Trần  | Design by <a href="" target="_blank">HaiNam</a></p>
    </div>
    <!-- //copyright -->
    <script src="~/Content/Log/Log.js"></script>
</body>
</html>