MayLocNuoc/Models/NhaCungCap.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MayLocNuoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaCungCap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhaCungCap()
        {
            this.sanphams = new HashSet<sanpham>();
        }
    
        public int idIfncc { get; set; }
        public string nameFull { get; set; }
        public int age { get; set; }
        public string number_phone { get; set; }
        public string adress { get; set; }
        public string ATM { get; set; }
        public int idhopdong { get; set; }
        public Nullable<bool> daxoa { get; set; }
        public string taikhoan { get; set; }
        public string About { get; set; }
    
        public virtual acc acc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sanpham> sanphams { get; set; }
    }
}

MayLocNuoc/Models/info.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MayLocNuoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class info
    {
        public int idIf { get; set; }
        public string nameFull { get; set; }
        public int age { get; set; }
        public string number_phone { get; set; }
        public string adress { get; set; }
        public string taikhoan { get; set; }
    
        public virtual acc acc { get; set; }
    }
}

MayLocNuoc/Controllers/NhaCungCapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MayLocNuoc.Models;
using PagedList;

namespace MayLocNuoc.Controllers
{
    public class NhaCungCapController : Controller
    {
        mayLocNuocEntities db = new mayLocNuocEntities();
        // GET: NhaCungCap
        [HttpGet]
        public ActionResult Index(string id ,int  page = 1, int size = 9)
        {
            if (id == null)
            {
                return RedirectToAction("Error","Error1");
            }
            else
            {
                int TL = Convert.ToInt32(id);
                ViewBag.id = TL;
                var model = db.sanphams.Where(m => m.idIfncc == TL).OrderBy(n => n.soluong).ToPagedList(page, size);
                return View(model);
            }
        }
        public ActionResult TrangChu(int page = 1, int size = 9)
        {
            if (save.taikhoan == null || save.taikhoan == "")
            {
                return RedirectToAction("DN", "QuanTri");
            }
            else
            {
                var id = db.NhaCungCaps.Where(n => n.taikhoan == save.taikhoan).FirstOrDefault();
                int TL = Convert.ToInt32(id.idIfncc);
                var model = db.sanphams.Where(m => m.idIfncc == TL).OrderBy(n => n.soluong).ToPagedList(page, size);
                return View(model);
            }
        }

        public ActionResult Product_To()
        {
            if (save.taikhoan == null || save.taikhoan == "")
            {
                return RedirectToAction("DN", "QuanTri");
            }
            else
            {
                return View();
            }
        }
        public ActionResult ThemSanPham()
        {
            if (save.taikhoan == null || save.taikhoan == "")
            {
                return RedirectToAction("DN", "QuanTri");
            }
            else
            {
                return View();
            }

        }
        // doanh thu////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        public ActionResult xemDoanhthu()
        {
            if (save.taikhoan == null || save.taikhoan == "")
            {
                return RedirectToAction("DN", "QuanTri");
            }
            else
            {
                return View();
            }
        }

        public ActionResult List_Product(int page = 1, int size = 9)
        {
            if (save.taikhoan == null || save.taikhoan == "")
            {
                return RedirectToAction("DN", "QuanTri");
            }
            else
            {
                var sanpham = db.sanphams.Where(n => n.idIfncc == (db.NhaCungCaps.Where(m => m.taikhoan == save.taikhoan).FirstOrDefault().idIfncc)).OrderBy(l=>l.ngaythem).ToPagedList(page, size);
                return View(sanpham);
            }
        }
        public ActionResult History(int page = 1, int size = 9)
        {
            if (save.taikhoan == null || save.taikhoan == "")
            {
                return RedirectToAction("DN", "QuanTri");
            }
            else
            {
                var damua = db.F_LayRaSanPhamCuaNhaCungCapMaKhachDaLapDatThanhCong(save.taikhoan).ToList();
                return View(damua);
            }
        }
        //san pham trong mot ngay trong thang

        public ActionResult Product_In_Day_inMonth(int? ngay, int? thang, int? nam)
        {
            int ngayhientai = Convert.ToInt32(DateTime.Now.Day);
            int Thanghientai = Convert.ToInt32(DateTime.Now.Month);
            int Namhientai = Convert.ToInt32(DateTime.Now.Year);
            if (save.taikhoan == null || save.taikhoan == "")
            {
                return RedirectToAction("DN", "QuanTri");
            }
            else
            {
                
                if ( thang == null || nam == null)
                {
                    ViewBag.ngay = ngayhientai;
                    ViewBag.thang = Thanghientai;
                    ViewBag.nam = Namhientai;
                    return View();
                }
                else
                {
                    if (ngay == null)
                    {
                        ViewBag.ngay = ngayhientai;
                        ViewBag.thang = thang;
                        ViewBag.nam = nam;
                        return View();
                    }
                    else
                    {
                        ViewBag.ngay = ngay;
                        ViewBag.thang = thang;
                        ViewBag.nam = nam;
                        return View();
                    }
                }
                

            }
        }
        //đánh Giá Của Tất cả sản phẩm chuyển qua trang chi tiết
        public ActionResult Evaluate_Product( int? sao , int? BanGi)
        {
            if (save.taikhoan == null || save.taikhoan == "")
            {
                return RedirectToAction("DN", "QuanTri");
            }
            else
            {
                if(sao ==null)
                {
                    ViewBag.Sao = 1;
                    ViewBag.BanGi = 10;
                    return View();
                }
                else if(BanGi==null)
                {
                    ViewBag.Sao = Convert.ToInt32(sao);
                    ViewBag.BanGi = 10;
                    return View();
                }
                else
                {
                    ViewBag.Sao = Convert.ToInt32(sao);
                    ViewBag.BanGi = Convert.ToInt32(BanGi);
                    return View();
                }
              
            }
        }
        ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////  

        public ActionResult SuaProduct(string ma)
        {
            if (save.taikhoan == null || save.taikhoan == "")
            {
                return RedirectToAction("DN", "QuanTri");
            }
            else
            {
                int ma1 = Convert.ToInt32(ma);
                var sanpham = db.sanphams.Where(n => n.idSP == ma1).FirstOrDefault();
                return View(sanpham);
            }
        }
        public ActionResult Info()
        {
            if (save.taikhoan == null || save.taikhoan == "")
            {
                return RedirectToAction("DN", "QuanTri");
            }
            else
            {
                return View();
            }
        }

        [HttpPost]
        //sua san pham//////////////////////////////////////////////////////////////////////////////////////////////
        public JsonResult docsanpham(string MaSanPham)
        {
            int MaSanPham1 = Convert.ToInt32(MaSanPham.Trim());
            var sa = db.sanphams.Where(n => n.idSP == MaSanPham1).FirstOrDefault();
            var sb = db.NhaCungCaps.Where(m => m.idIfncc == sa.idIfncc).FirstOrDefault();
            if (sb.taikhoan == save.taikhoan)
            {

            }
            else
            {

            }
            var xyz = new string[sa.idSP];
            return Json(xyz);
        }
        //ket thuc sua san pham///////////////////////////////////////////////////////////////////////////////////
        //them san pham vao /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        public JsonResult Add_product(string name_product,
                                      string length_product,
                                      string with_product,
                                      string height_product,
                                      string title_product,
                                      string number_product,
                                      string core_product,
                                      string producttion_product,
                                      string speed_product,
                                      string technology_product,
                                      string pump_product,
                                      string price_product,
                                      string brand_product,
                                      string quality_product,
                                      string where_production,
                                      string free_product,
                                      string number_free_product,
                                      string Imgchinh,
                                      string Img1,
                                      string Img2,
                                      string Img3,
                                      string Img4)
        {
            string trave = "";
            //tim kiem nha cung cap theo tai khoan hien co
            /*
             * 1 là tài khoản hiện tại rỗng
             * 2 là nha cung cấp chưa đăng ký
             * 3 là đã gặp vấn đề về dữ liệu
             * 4 laf hoàn thành
             */
            if (save.taikhoan == null || save.taikhoan == "")
            {
                trave = "1";
            }
            else
            {

                var manhacungcap = db.NhaCungCaps.Where(n => n.taikhoan == save.taikhoan).FirstOrDefault().idIfncc;
                if (manhacungcap == null)
                {
                    trave = "2";
                }
                else
                {
                    try
                    {
                        sanpham sp = new sanpham();
                        sp.tensp = name_product;
                        sp.dai = Convert.ToInt32(length_product);
                        sp.rong = Convert.ToInt32(with_product);
                        sp.cao = Convert.ToInt32(height_product);
                        sp.tieude = title_product;
                        sp.soluong = Convert.ToInt32(number_product);

MayLocNuoc/Views/NhaCungCap/Info.cshtml
@{
    ViewBag.Title = "Info";
    Layout = "~/Views/NhaCungCap/layoutNCC.cshtml";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-6 col-xs-12 col-md-6 col-sm-12" style="padding:20px;">
            <div>
                <img src="" id="ImgShowChinhInFoNCC" style="height:70%; top:0px;width:100%;" />
                <div style="height:10%; padding-top:2%;width:100%;">
                    <input type="file" name="file" id="filechinh12345" class="inputfile " />
                    <label for="filechinh12345" id="filechinh" class="btn btn-default">ảnh Chính</label>
                </div>
            </div>
        </div>
        <div class=" col-lg-6 col-xs-12 col-md-6 col-sm-12" style="float:left;">
            <b><i>Cơ Bản</i></b>
            <input type="text" placeholder="Tài Khoản" style=" width:100%;" />
            <input type="text" placeholder="Tên " style=" width:100%;" />
            <input type="number" placeholder="Tuổi" style=" width: 100%;" />
            <input type="number" placeholder="Số Điện thoại" style=" width:100%;" />
            <input type="text" placeholder="Địa chỉ" style=" width:100%;" />
            <input type="email" placeholder="Email" style=" width:100%;" />
            <input type="number" placeholder="ATM" style=" width: 100%;" />
        </div>
    </div>
    <input type="submit" id="CapNhatThongTinNhaCungCap" class="btn btn-outline-success" value="Cập Nhật" style=" width: 100%;" />
    <script type="text/javascript" src="~/Content/NCC/all/js/jquery-2.1.4.min.js"></script>  
</div>

MayLocNuoc/Views/NhaCungCap/Lay_out_DoanhThu.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Nhà Cung Cấp Máy Lọc Nước Sơn Trần </title>
    <!-- for-mobile-apps -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="" />
    <script type="application/x-javascript">
        addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
               function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- //for-mobile-apps -->
    <link href="~/Content/NCC/all/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/Content/NCC/all/css/font-awesome.css" rel="stylesheet">
    <link rel="stylesheet" href="~/Content/NCC/all/css/lightbox.css" type="text/css" media="all" /><!--gallery-popup-css-->
    <link href="~/Content/NCC/all/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <!--fonts-->
    <link href="//fonts.googleapis.com/css?family=Six+Caps" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Josefin+Sans:100,300,400,600,700" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Lato:300,400,700,900" rel="stylesheet">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <!--//fonts-->
</head>
<body>
    <!-- banner -->
    <div class="banner" id="home">
        <div class="container">
            <div class="header">
                <div class="hainam_agile_logo">
                    <h1><a href="@Url.Action("Index","Product")">SƠN TRẦN<span>Máy Lọc Nước</span></a></h1>
                </div>
                <div class="hainam_menu">
                    <div class="mobile-nav-button">
                        <div class="mobile-nav-button__line"></div>
                        <div class="mobile-nav-button__line"></div>
                        <div class="mobile-nav-button__line"></div>
                    </div>
                    <nav class="mobile-menu">
                        <ul>
                            <li class="active"><a href="@Url.Action("TrangChu","NhaCungCap")" class=" scroll">Home</a></li>
                            <li><a href="@Url.Action("xemDoanhthu", "NhaCungCap")" class="scroll">Doanh Thu</a></li>
                            <li><a href="@Url.Action("Info","NhaCungCap")" class="scroll">Thông Tin Bản Thân</a></li>
                            <li><a href="@Url.Action("ThemSanPham","NhaCungCap")" class="scroll">Thêm Sản Phẩm</a></li>

                        </ul>
                    </nav>
                </div>
                <div class="clearfix"> </div>
            </div>
            <div class="agile_banner_info">
                <h3><span>C</span>hào  <span>M</span>ừng  <span>N</span>hà  <span>C</span>ung  Cấp   Trần Hữu Sơn </h3>
            </div>
        </div>
    </div>
    <style>
        .banner {
            background: url(../Content/NCC/all/images/4.jpg) no-repeat 0px 0px;
            background-size: cover;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            -ms-background-size: cover;
            min-height: 770px;
            position: relative;
        }
    </style>
    <!-- //banner -->
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <div class="container-fluid">
        <div class="row">
            @RenderBody()
        </div>
    </div>
    <div class="footer-bottom wtrhee-agileinfo">
        <div class="container">
            <p class="col-md-6 copy">Máy Lọc Nước Sơn Trần  | Design  <a href="">HaiNam</a></p>
            <div class=" col-md-3 top-hainamls">
                <a href="#home" class="scroll"><span class="glyphicon glyphicon-chevron-up" aria-hidden="true"></span>Lên Đầu Trang</a>
            </div>
        </div>
    </div>
    <!--//footer-->
    <!-- js -->
    <script type="text/javascript" src="~/Content/NCC/all/js/jquery-2.1.4.min.js"></script>


    <!-- Navigation-JavaScript -->
    <!-- menu -->
    <script>
        $(document).ready(function () {
            $('.mobile-nav-button').on('click', function () {
                $(".mobile-nav-button .mobile-nav-button__line:nth-of-type(1)").toggleClass("mobile-nav-button__line--1");
                $(".mobile-nav-button .mobile-nav-button__line:nth-of-type(2)").toggleClass("mobile-nav-button__line--2");
                $(".mobile-nav-button .mobile-nav-button__line:nth-of-type(3)").toggleClass("mobile-nav-button__line--3");

                $('.mobile-menu').toggleClass('mobile-menu--open');
                return false;
            });
        });
    </script>
    <!-- //menu -->
    <!-- //Navigation-JavaScript -->
    <!--gallery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <script src="~/Content/NCC/all/js/lightbox.js"></script>
    <!-- //gallery -->
    <script type="text/javascript">
        $(window).load(function () {
            $("#flexiselDemo1").flexisel({
                visibleItems: 4,
                animationSpeed: 1000,
                autoPlay: true,
                autoPlaySpeed: 3000,
                pauseOnHover: true,
                enableResponsiveBreakpoints: true,
                responsiveBreakpoints: {
                    portrait: {
                        changePoint: 480,
                        visibleItems: 1
                    },
                    landscape: {
                        changePoint: 640,
                        visibleItems: 2
                    },
                    tablet: {
                        changePoint: 768,
                        visibleItems: 3
                    }
                }
            });

        });
    </script>
    <script type="text/javascript" src="~/Content/NCC/all/js/jquery.flexisel.js"></script>
    <!-- jarallax-js -->
    <script src="~/Content/NCC/all/js/jarallax.js"></script>
    <script src="~/Content/NCC/all/js/SmoothScroll.min.js"></script>
    <script type="text/javascript">
        /* init Jarallax */
        $('.jarallax').jarallax({
            speed: 0.5,
            imgWidth: 1366,
            imgHeight: 768
        })
    </script>
    <!-- //jarallax-js -->
    <!-- start-smoth-scrolling -->
    <script type="text/javascript" src="~/Content/NCC/all/js/move-top.js"></script>
    <script type="text/javascript" src="~/Content/NCC/all/js/easing.js"></script>
    <!-- start-smoth-scrolling -->
    <script src="~/Content/NCC/all/jsThemSanPham/inDayMonth.js"></script>
    <script src="~/Content/NCC/all/jsThemSanPham/DG.js"></script>
</body>
</html>

MayLocNuoc/Views/NhaCungCap/List_Product.cshtml
@using MayLocNuoc.Models;
@using PagedList.Mvc;
@model PagedList.IPagedList<sanpham>
@{
    ViewBag.Title = "List_Product";
    Layout = "~/Views/NhaCungCap/Lay_out_DoanhThu.cshtml";
}
<div style="width:100%;">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link " href="@Url.Action("xemDoanhthu","NhaCungCap")">Doang Thu Tổng Quan</a>
        </li>
        <li class="nav-item">
            <a class="nav-link  " href="@Url.Action("Product_In_Day_inMonth","NhaCungCap")">Theo Tháng</a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="@Url.Action("Evaluate_Product","NhaCungCap")">Đánh Giá</a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="@Url.Action("Product_To","NhaCungCap")">Sản Phẩm Yêu Cầu </a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="@Url.Action("List_product","NhaCungCap")">Danh sách</a>
        </li>
    </ul>
</div>
<table class="table table-striped table-dark" style="text-align:center;">
    <thead>
        <tr>
            <th scope="col">Ảnh Sản Phẩm</th>
            <th scope="col">tên sản Phẩm</th>
            <th scope="col">Giá</th>
            <th scope="col">Mã Giảm Giá</th>
            <th scope="col">Ngày Đăng</th>
            <th scope="col">Sử Lý</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var key in Model)
        {
            <tr>
                <td style="width:25%;"><img src="@key.anhsanpham1" style="width:100%; height:30%;" /> </td>
                <td>@key.tensp</td>
                <td>@key.gia</td>
                <td>@key.magiamgia</td>
                <td>@key.ngaythem</td>
                <td style="width:10%;">
                    <a href="@Url.Action("Index","chiTiet", new {id=key.idSP})">Chi Tiết</a><br /><hr />
                    <a href="@Url.Action("SuaProduct","NhaCungCap", new {ma=key.idSP})">Chỉnh sửa</a><br /><hr />
                </td>
            </tr>

        }

    </tbody>
</table>
<div style="margin-left:40%;"> @Html.PagedListPager(Model, Page => Url.Action("List_Product", new { Page }))</div>

MayLocNuoc/Views/NhaCungCap/Product_To.cshtml
@using MayLocNuoc.Models;
@model daMua
@{
    ViewBag.Title = "Product To";
    Layout = "~/Views/NhaCungCap/Lay_out_DoanhThu.cshtml";
}
<div style="width:100%;">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link " href="@Url.Action("xemDoanhthu","NhaCungCap")">Doang Thu Tổng Quan</a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="@Url.Action("Product_In_Day_inMonth","NhaCungCap")">Theo Tháng</a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="@Url.Action("Evaluate_Product","NhaCungCap")">Đánh Giá</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="@Url.Action("Product_To","NhaCungCap")">Sản Phẩm Yêu Cầu </a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="@Url.Action("List_Product","NhaCungCap")">Danh sách</a>
        </li>
    </ul>
</div>
<i> <h1><p style="text-align:center; color:rgba(69, 186, 224, 0.91)">Sản Phẩm Được Yêu Cầu</p></h1></i>
<table class="table table-dark">
    @{
        mayLocNuocEntities db = new mayLocNuocEntities();
        var dangmua1 = db.F_LayRaSanPhamCuaNhaCungCapMaKhachDaMua(save.taikhoan);
    }
    @foreach (var key in dangmua1)
    {
        <tbody>
            <tr>
                <td style="width:30%; height:auto;" colspan="2" rowspan="7">
                    @{
                        var tensap = db.sanphams.Where(m => m.idSP == key.idSP).FirstOrDefault();
                    }
                    <img style="width:100%; height:auto;" src="@tensap.anhsanpham1" />
                </td>
                <td colspan="5">Tên Sản Phẩm : @tensap.tensp</td>
            </tr>
            <tr>
                <td>Giá : @key.gia</td>
                <td>Số Phần Trăm Giảm Giá : @key.sophantram (%)</td>
                <td>Số Lượng : @key.soluong</td>
                @{
                    var tongso = ((key.gia * (key.sophantram + 100)) / 100) * key.soluong;
                }
                <td colspan="2">Tổng : @tongso</td>
            </tr>
            <tr>
                @{
                    var khachHang = db.infoes.Where(k => k.taikhoan == save.taikhoan).FirstOrDefault();
                }
                <td colspan="2">Tên Khách: @khachHang.nameFull</td>
                <td colspan="3">Địa chỉ : @khachHang.adress</td>
            </tr>
            <tr>
                <td colspan="1">Bên Khách</td>
                <td colspan="1">Ngay Đặt : @key.ngaymua</td>
                <td colspan="1">Thời Gian Chờ : 3-7 ngày</td>
            </tr>
            <tr>
                <td colspan="1">Bên Nhà Cung Cấp</td>
                @if (key.dangChuanBi == false && key.dangVanChuyen == false)
                {
                    <td colspan="1">Đang Chuẩn Bị : Chưa</td>
                    <td colspan="1">Đang Vận chuyển : Chưa</td>
                }
                else if (key.dangChuanBi == true && key.dangVanChuyen == false)
                {
                    <td colspan="1">Đang Chuẩn Bị : Đã Xong</td>
                    <td colspan="1">Vận chuyển : Xác Nhận</td>
                }
                else if (key.dangChuanBi == true && key.dangVanChuyen == true)
                {
                    <td colspan="1">Đang Chuẩn Bị : Đã Xong</td>
                    <td colspan="1">Đang Vận chuyển : Xác Nhận</td>
                }
                <td colspan="2">Ngày Lắp Đặt Dự Kiến (Tháng/ngày/Năm) : @key.ngayLapDat</td>
            </tr>
            <tr>
                <td colspan="1">Ngày Lắp</td>
                <td colspan="1"><input class="nam btn btn-block" data-id="@key.idDM" min="2020" max="2030" style="background-color:white; color:black; text-align:left;" type="number" value="2020" /></td>
                <td colspan="1"><input class="thang btn btn-block" data-id="@key.idDM" min="1" max="12" style="background-color:white; color:black; text-align:left;" type="number" value="12" /></td>
                <td colspan="1"><input class="ngay btn btn-block" data-id="@key.idDM" min="1" max="31" style="background-color:white; color:black; text-align:left;" type="number" value="1" /></td>
                <td colspan="1"> <input class=" thayDoiNgayThan btn btn-success" data-id="@key.idDM" data-idcuasanpham="@key.idSP" type="submit" value="Chỉnh Sửa" /></td>
            </tr>
            <tr>
                <td><input class="DaLapDat btn btn-success" data-id="@key.idDM" data-idcuasanpham="@key.idSP" type="submit" value="Đã Lắp Đặt" /></td>
                <td><input class="DangVanChuyen btn btn-success" data-id="@key.idDM" data-idcuasanpham="@key.idSP" type="submit" value="Đang Vận Chuyển" /></td>
                <td><a href="@Url.Action("Index","ChiTiet",new {id=key.idSP})"><input class="btn btn-success" type="submit" value="Đánh Giá" /></a></td>
            </tr>
        </tbody>
    }
</table>

MayLocNuoc/Views/NhaCungCap/xemDoanhthu.cshtml
@{
    ViewBag.Title = "Product_In_Day_inMonth";
    Layout = "~/Views/NhaCungCap/Lay_out_DoanhThu.cshtml";
}
<div style="width:100%;">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active" href="@Url.Action("xemDoanhthu","NhaCungCap")">Doang Thu Tổng Quan</a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="@Url.Action("Product_In_Day_inMonth","NhaCungCap")">Theo Tháng</a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="@Url.Action("Evaluate_Product","NhaCungCap")">Đánh Giá</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="@Url.Action("Product_To","NhaCungCap")">Sản Phẩm Yêu Cầu </a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="@Url.Action("List_Product","NhaCungCap")">Danh sách</a>
        </li>
    </ul>
</div>