MayLocNuoc/Models/giohang.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MayLocNuoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class giohang
    {
        public int idGH { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<bool> daxoa { get; set; }
        public Nullable<int> idSP { get; set; }
        public string taikhoan { get; set; }
    
        public virtual acc acc { get; set; }
        public virtual sanpham sanpham { get; set; }
    }
}

MayLocNuoc/Controllers/GioHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MayLocNuoc.Models;

namespace MayLocNuoc.Controllers
{
    public class GioHangController : Controller
    {
        mayLocNuocEntities db = new mayLocNuocEntities();
        // GET: GioHang
        public ActionResult MyCart()
        {
            if(save.taikhoan==null || save.taikhoan=="")
            {
                return RedirectToAction("Log", "DangNhap");
            }
            else
            {
                return View();
            }            
        }

        [HttpPost]
        public JsonResult addProduct( string idGioHang, string soluong)
        {

            /*
             * 1 loi he thong
             * 2 gio hang tim ko thay na pham cos tai khoan va ma hang nhu tren 
             * 3 tai khoan chua dang nhap
             * 4 la thanh cong chuyen den trang da mua 
             */
            string trave = "";
            if (save.taikhoan==""|| save.taikhoan==null) {
               trave="3";
            }
            else
            {
                try
                {
                    int concac = Convert.ToInt32(idGioHang);
                    var bcg = db.dangMuas.Where(n => n.taikhoan == save.taikhoan && n.idDM == concac);
                    if (bcg.Count() == 0)
                    {
                        trave = "2";
                    }
                    else
                    {
                        daMua dam = new daMua();
                        dam.soluong = Convert.ToInt32(soluong);
                        dam.gia = bcg.FirstOrDefault().gia;
                        dam.sophantram = bcg.FirstOrDefault().sophantram;
                        dam.dangChuanBi = true;
                        dam.ngaymua = DateTime.Now;
                        dam.ngayLapDat = DateTime.Now.Add(new TimeSpan(1, 0, 0, 0));
                        dam.dangVanChuyen = false;
                        dam.daxoa = false;
                        dam.idSP = bcg.FirstOrDefault().idSP;
                        dam.taikhoan = save.taikhoan;

                        db.daMuas.Add(dam);

                        db.SaveChanges();
                        bcg.FirstOrDefault().daxoa = true;
                        db.SaveChanges();
                        trave = "4";
                    }
                }
                catch (Exception)
                {

                    trave = "1";
                }
            }
            return Json(trave);
        } 

        public JsonResult Deletes(string idGioHang)
        {
            /*
            * 1 loi he thong
            * 2 gio hang tim ko thay na pham cos tai khoan va ma hang nhu tren 
            * 3 tai khoan chua dang nhap
            * 4 la thanh cong and thong bao
            */
            string trave = "";
            if (save.taikhoan == "" || save.taikhoan == null)
            {
                trave = "3";
            }
            else
            {
                try
                {
                    int concac = Convert.ToInt32(idGioHang);
                    var bcg = db.dangMuas.Where(n => n.taikhoan == save.taikhoan && n.idDM == concac);
                    if (bcg.Count() == 0)
                    {
                        trave = "2";
                    }
                    else
                    {
                        bcg.FirstOrDefault().daxoa = true;
                        db.SaveChanges();
                        trave = "4";
                    }
                }
                catch (Exception)
                {

                    trave = "1";
                }
            }
            return Json(trave);
        }
    }
}

MayLocNuoc/Views/GioHang/MyCart.cshtml
@using MayLocNuoc.Models;

<!doctype html>
<html lang="en">
<head>
    <title>Title</title>
    <!-- Required meta tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <!-- First include jquery js -->
    <script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
    <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <link href="~/Content/home/css/font-awesome.min.css" rel="stylesheet" />
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body style="background-color:#0094ff;">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="@Url.Action("Index","Product")">Sơn Trần</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="@Url.Action("Index","Product")">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="@Url.Action("DangMua","DaMua")" tabindex="-1" aria-disabled="true">Đang Chờ</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="@Url.Action("LichSu","DaMua")" tabindex="-1" aria-disabled="true">Lịch sử</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="@Url.Action("MyCart","GioHang")" tabindex="-1" aria-disabled="true">Giỏ Của Tôi</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="@Url.Action("Log","DangNhap")" tabindex="-1" aria-disabled="true">Tài Khoản</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="@Url.Action("Index","TroGiup")" tabindex="-1" aria-disabled="true">Trợ Giúp</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
    <table class="table table-striped table-dark">
        <thead>
            <tr>
                <th scope="col">Mua</th>
                <th scope="col">Tên</th>
                <th scope="col">Ảnh</th>
                <th scope="col">Giá</th>
                <th scope="col">Giảm Giá</th>
                <th scope="col">Số Lượng/Tổng</th>
                <th scope="col">Delete</th>
            </tr>
        </thead>
        <tbody>
            @{
                mayLocNuocEntities db = new mayLocNuocEntities();
                var ggg = db.dangMuas.Where(n => n.taikhoan == save.taikhoan && n.daxoa == false).ToList();
            }

            @foreach (var key in ggg)
            {
                <tr>
                    @{
                        var anhsp = db.sanphams.Where(m => m.idSP == key.idSP).FirstOrDefault();
                    }
                    <th scope="row"><button data-id="@key.idDM" class="CamOnMuaSanPham fa fa-download" style="color:#4cff00; background-color:rgba(0, 0, 0, 0.00)"></button></th>
                    <td>@anhsp.tensp</td>
                    <td><img style="width:100px; height:100px; " src="@anhsp.anhsanpham1" /></td>
                    <td class="GiaCuaSanPham" data-id="@key.idDM">@key.gia</td>
                    <td>@key.sophantram</td>
                    @{
                        var tong = (key.gia * (100 - key.sophantram ) / 100) * key.soluong;
                    }
                    <td width="5%">
                        <input id="@key.idDM" type="number" min="0" max="10" value="@key.soluong" style="background-color:rgba(0, 0, 0, 0.00); color:white;" class="number_product" />
                        <i class="HomNayDuocNghi fa fa-check" data-idsanpham="@key.idSP" data-id="@key.idDM" data-gia-id="@key.gia" data-giam-gia="@key.sophantram"></i>

                        <b id="@key.idSP">@tong</b>
                    </td>
                    <td>
                        <button class="XinLoiViBatKeLyDoGi fa fa-times" data-id="@key.idDM" style="color:darkred; background-color:rgba(0, 0, 0, 0.00)"></button>
                    </td>
                </tr>
            }
        </tbody>
    </table>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="~/Content/chiTiet/js/dungKhocMotMinhEmOi.js"></script>
</body>
</html>